# Generated by Django 4.1.7 on 2023-03-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('course_id', models.UUIDField()),
                ('student_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentParents',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('parent_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
    ]
