# Generated by Django 4.1.7 on 2023-03-31 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_courses_course_rename_enrollments_enrollment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentParents',
            new_name='StudentParent',
        ),
    ]
