# Generated by Django 4.1.7 on 2023-04-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_studentparents_studentparent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='student_id',
            new_name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='classes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
