# Generated by Django 4.1.7 on 2023-04-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_enrollment_course_alter_enrollment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
